// Comprehensive YDS word/phrase database
// Covers all options appearing in the 2026 YDS Exam 1

export interface WordEntry {
  meaning_tr: string
  field: string           // semantic field
  collocations: string[]
  memory_trick: string
  trap_word?: string
  trap_explanation?: string
  template_sentences: string[]  // ____ marks the blank
}

export const WORD_DB: Record<string, WordEntry> = {
  // ── VOCABULARY ─────────────────────────────────────────────────────────────
  endure: {
    meaning_tr: 'dayanmak, uzun süre varlığını sürdürmek',
    field: 'duration / persistence',
    collocations: ['endure in the environment', 'endure hardship', 'endure for centuries', 'endure through time'],
    memory_trick: 'EN-DUR → "EN uzun DURe" → çevrede yıllarca duruyor, gitmez',
    trap_word: 'accelerate',
    trap_explanation: '"accelerate" hızlandırır ama "endure" uzun süre KALMAyı ifade eder',
    template_sentences: [
      'Plastic waste can ____ in the oceans for hundreds of years without breaking down.',
      'These ancient traditions have managed to ____ despite the rapid changes of modern society.',
      'The effects of radiation can ____ in the affected area for decades.',
    ],
  },
  assemble: {
    meaning_tr: 'toplamak, bir araya getirmek / gelmek',
    field: 'gathering / construction',
    collocations: ['assemble a team', 'assemble in the square', 'assemble parts', 'assemble data'],
    memory_trick: 'ASSEMBLE → A + SEMBLER (Fransızca = benzer) → "benzer şeyleri BİR ARAYA TOPLA"',
    trap_word: 'endure',
    trap_explanation: 'assemble = bir araya gelme/toplama; endure = uzun süre kalma — çok farklı anlamlar',
    template_sentences: [
      'Scientists ____ data from multiple sources to form a comprehensive theory.',
      'Hundreds of protesters ____ in the central square to demonstrate peacefully.',
    ],
  },
  accelerate: {
    meaning_tr: 'hızlandırmak, ivmelendirmek',
    field: 'speed / change',
    collocations: ['accelerate the process', 'accelerate growth', 'accelerate climate change', 'accelerate development'],
    memory_trick: 'ACCELERATE → ACCEL + RATE → "oran artıyor" = hız kazanıyor',
    trap_word: 'endure',
    trap_explanation: '"accelerate" = hızlandırmak (değişim var); "endure" = yerinde kalmak (değişim yok)',
    template_sentences: [
      'New digital technologies can ____ the spread of information across the globe.',
      'Climate change is likely to ____ the melting of polar ice caps.',
    ],
  },
  elaborate: {
    meaning_tr: 'ayrıntılandırmak, genişletmek; ayrıntılı',
    field: 'explanation / detail',
    collocations: ['elaborate on a point', 'elaborate design', 'elaborate explanation', 'elaborate further'],
    memory_trick: 'E-LABOR-ATE → "emek verip AYRINTILI yazmak" → labor = emek',
    trap_word: 'accelerate',
    trap_explanation: 'elaborate = daha fazla AÇIKLAMAK; context yıllarca dayanmayı anlatıyor, açıklama değil',
    template_sentences: [
      'The professor asked the student to ____ on her hypothesis about climate change.',
      'The artist created an ____ design with hundreds of intricate patterns.',
    ],
  },
  'embark on': {
    meaning_tr: 'başlamak, girişmek, yola çıkmak',
    field: 'starting / undertaking',
    collocations: ['embark on a journey', 'embark on a project', 'embark on a career', 'embark on research'],
    memory_trick: 'em-BARK → köpek havlıyor ve bir YOLCULUĞA ÇIKIYOR (gemiye biniyor)',
    trap_word: 'set back',
    trap_explanation: '"embark on" = bir şeye girişmek (pozitif başlangıç); "set back" = geciktirmek (negatif)',
    template_sentences: [
      'The research team decided to ____ an ambitious study of ocean biodiversity.',
      'After graduation, she chose to ____ a career in neuroscience.',
    ],
  },
  'set back': {
    meaning_tr: 'geri atmak, geciktirmek, aksatmak',
    field: 'delay / obstacle',
    collocations: ['set back the progress', 'set back development', 'set back recovery'],
    memory_trick: '"set BACK" = geri koymak → ilerlemeyi GERIYE ITIR',
    trap_word: 'embark on',
    trap_explanation: '"set back" = olumsuz etki/gecikme; "embark on" = girişmek (olumlu başlangıç)',
    template_sentences: [
      'The unexpected funding cut could seriously ____ the development of the new vaccine.',
    ],
  },
  'get by': {
    meaning_tr: 'idare etmek, geçinmek, bir şekilde başarmak',
    field: 'survival / management',
    collocations: ['get by on a low income', 'get by without help', 'get by somehow'],
    memory_trick: '"GET BY" = sadece yanından geçmek → "minimum düzeyde idare etmek"',
    trap_word: 'embark on',
    trap_explanation: '"get by" = zorluğa rağmen idare etmek; "embark on" = hevesle başlamak — zıt tonlar',
    template_sentences: [
      'Despite having limited resources, the community managed to ____ during the crisis.',
    ],
  },
  'put down': {
    meaning_tr: 'bastırmak, aşağılamak; yazmak (not almak)',
    field: 'suppression / note',
    collocations: ['put down a rebellion', 'put down your thoughts', 'put down roots'],
    memory_trick: '"PUT DOWN" = aşağıya koy → hem not alma hem de bastırma/küçük düşürme',
    trap_word: 'embark on',
    trap_explanation: '"put down" = bastırmak ya da not almak; "embark on" = başlamak — farklı',
    template_sentences: [
      'The government used force to ____ the uprising in the eastern province.',
    ],
  },
  'ease off': {
    meaning_tr: 'yavaşlamak, azalmak, hafiflemek',
    field: 'reduction / decrease',
    collocations: ['ease off the pressure', 'ease off gradually', 'pain eases off'],
    memory_trick: '"EASE OFF" = rahatlık kazanmak, giderek HAFIFLEMEK',
    trap_word: 'embark on',
    trap_explanation: '"ease off" = azalmak; "embark on" = başlamak — tam ters yön',
    template_sentences: [
      'The heavy rain began to ____ as the storm passed over the city.',
    ],
  },
  compliant: {
    meaning_tr: 'uyumlu, kurallara uyan, boyun eğen',
    field: 'obedience / conformity',
    collocations: ['compliant with regulations', 'fully compliant', 'legally compliant'],
    memory_trick: 'COMPLY + ANT → "kurallarla UYUMLU olan" → comply = uymak',
    trap_word: 'resilient',
    trap_explanation: '"compliant" = kurallara UYMAK; "resilient" = zorluklara DAYANMAK — çok farklı',
    template_sentences: [
      'All products must be ____ with the new safety regulations before distribution.',
    ],
  },
  resilient: {
    meaning_tr: 'dirençli, dayanıklı, toparlanabilen',
    field: 'strength / recovery',
    collocations: ['resilient economy', 'resilient community', 'resilient infrastructure', 'prove resilient'],
    memory_trick: 'RE-SILIENT → yay gibi: basarsın, tekrar ZIPLar = TOPARLANMA gücü var',
    trap_word: 'compliant',
    trap_explanation: '"resilient" = zorluk sonrası toparlanmak; "compliant" = kurallara uymak — fark var',
    template_sentences: [
      'The coastal community proved ____ in the face of repeated natural disasters.',
      'A ____ ecosystem can recover quickly after a disruption like wildfire.',
    ],
  },
  sanctioned: {
    meaning_tr: 'onaylanmış, izin verilmiş; yaptırım uygulanan',
    field: 'official approval / penalty',
    collocations: ['officially sanctioned', 'sanctioned by the government', 'sanctioned activities'],
    memory_trick: 'SANCTION → hem "onay" hem "ceza" (iki zıt anlam!) → BAĞLAM belirler',
    trap_word: 'compliant',
    trap_explanation: '"sanctioned" = resmi olarak onaylanmış; "compliant" = uymak — farklı odaklar',
    template_sentences: [
      'The clinical trials were officially ____ by the national health authority.',
    ],
  },
  legible: {
    meaning_tr: 'okunabilir, okunaklı',
    field: 'readability',
    collocations: ['legible handwriting', 'barely legible', 'clearly legible'],
    memory_trick: 'LEGIBLE → "LEG + IBLE" → "okuma LEYebilirsin" → "leg-" = okumak (legal, legend)',
    trap_word: 'resilient',
    trap_explanation: '"legible" = okunabilirlik (yazı için); "resilient" = dayanıklılık — tamamen farklı',
    template_sentences: [
      'The ancient inscription was barely ____ after centuries of erosion.',
    ],
  },
  presumption: {
    meaning_tr: 'varsayım, üstlenme; küstahlık',
    field: 'assumption / arrogance',
    collocations: ['presumption of innocence', 'bold presumption', 'wild presumption'],
    memory_trick: 'PRE + SUMPTION → "önceden ALMIŞ olmak" → henüz kanıtlanmamış VARSAYIM',
    trap_word: 'proximity',
    trap_explanation: '"presumption" = kanıtsız varsayım; "proximity" = mesafe/yakınlık — anlam farkı büyük',
    template_sentences: [
      'The court operates on the ____ of innocence until proven guilty.',
    ],
  },
  proximity: {
    meaning_tr: 'yakınlık, yakın mesafe',
    field: 'distance / closeness',
    collocations: ['in close proximity', 'proximity to the city', 'physical proximity'],
    memory_trick: 'PROX-IMITY → "PROXimate" = yakın → YAKINLIK',
    trap_word: 'degradation',
    trap_explanation: '"proximity" = yakınlık (mesafe); "degradation" = bozulma/kötüleşme — zıt anlamlı bile değil',
    template_sentences: [
      'The school\'s ____ to the city centre made it accessible for most students.',
    ],
  },
  degradation: {
    meaning_tr: 'bozunma, bozulma, çöküş, düşme',
    field: 'decline / deterioration',
    collocations: ['environmental degradation', 'soil degradation', 'degradation of quality', 'degradation of values'],
    memory_trick: 'DEGRADE + ATION → "derecesi düşüyor" = BOZUNMA, çürüme',
    trap_word: 'proximity',
    trap_explanation: '"degradation" = kötüleşme süreci; "proximity" = konumsal yakınlık — çok farklı',
    template_sentences: [
      'The rapid ____ of forest ecosystems is threatening hundreds of species.',
      'Scientists are studying the ____ of plastics in ocean environments.',
    ],
  },
  sceptically: {
    meaning_tr: 'şüpheyle, kuşkuyla',
    field: 'doubt / disbelief',
    collocations: ['view sceptically', 'approach sceptically', 'receive sceptically'],
    memory_trick: 'SCEPTIC → "şüpheci kişi" → şüpheyle BAKMAK',
    trap_word: 'eloquently',
    trap_explanation: '"sceptically" = şüpheyle; "eloquently" = etkili/güzel biçimde konuşmak — zıt tonlar',
    template_sentences: [
      'Many scientists initially viewed the new theory ____ before examining the evidence.',
    ],
  },
  eloquently: {
    meaning_tr: 'akıcı ve etkileyici biçimde, belagatlı',
    field: 'speech / expression',
    collocations: ['speak eloquently', 'argue eloquently', 'write eloquently'],
    memory_trick: 'ELO-QUENTLY → "ELO score yüksek konuşma" → belagatlı, çok etkileyici',
    trap_word: 'sceptically',
    trap_explanation: '"eloquently" = nasıl konuşulduğu (iyi); "sceptically" = nasıl yaklaşıldığı (kuşkuyla)',
    template_sentences: [
      'The senator spoke ____ about the need for immediate climate action.',
    ],
  },
  superficially: {
    meaning_tr: 'yüzeysel olarak, derine inmeden',
    field: 'shallow / surface-level',
    collocations: ['superficially similar', 'examine superficially', 'understand superficially'],
    memory_trick: 'SUPER + FACIAL → "yüzey(face) üstünde" → derine INMEDEN, YÜZEYSEL',
    trap_word: 'variably',
    trap_explanation: '"superficially" = derinlik eksikliği; "variably" = değişkenlik — farklı boyutlar',
    template_sentences: [
      'The two theories appear ____ similar, but they differ fundamentally in their core assumptions.',
    ],
  },
  variably: {
    meaning_tr: 'değişken biçimde, tutarsız olarak',
    field: 'inconsistency / variation',
    collocations: ['respond variably', 'perform variably', 'distributed variably'],
    memory_trick: 'VARIABLE + LY → değişken → DEĞİŞKEN BİÇİMDE',
    trap_word: 'superficially',
    trap_explanation: '"variably" = tutarsız/değişken; "superficially" = yüzeysel — farklı sorunlar',
    template_sentences: [
      'Patients responded ____ to the new treatment, with outcomes ranging from excellent to poor.',
    ],
  },
  faintly: {
    meaning_tr: 'hafifçe, belirsizce, zayıfça',
    field: 'weak / dim',
    collocations: ['faintly visible', 'faintly heard', 'faintly reminiscent', 'smile faintly'],
    memory_trick: 'FAINT = bayılmak, solmak → çok ZAYIF, belirsiz',
    trap_word: 'eloquently',
    trap_explanation: '"faintly" = zayıf/belirsiz şekilde; "eloquently" = güçlü ve etkileyici şekilde — tam karşıt',
    template_sentences: [
      'She could ____ detect the smell of smoke coming from the neighbouring building.',
    ],
  },
  conciliation: {
    meaning_tr: 'uzlaştırma, barışma, gönül alma',
    field: 'peace / reconciliation',
    collocations: ['seek conciliation', 'conciliation process', 'spirit of conciliation'],
    memory_trick: 'CON + CILIA → "GÖZ KIRPARAK birini yanına çekme" → barışma, UZLAŞTIRMA',
    trap_word: 'enforcement',
    trap_explanation: '"conciliation" = anlaşma yolu; "enforcement" = zorlama yolu — zıt yaklaşımlar',
    template_sentences: [
      'The two parties agreed to enter a ____ process rather than take the dispute to court.',
    ],
  },
  enforcement: {
    meaning_tr: 'uygulama, yaptırım, zorla yürürlüğe koyma',
    field: 'authority / compulsion',
    collocations: ['law enforcement', 'strict enforcement', 'enforcement agency', 'enforcement of regulations'],
    memory_trick: 'EN + FORCE + MENT → "güç kullanarak UYGULAMAK" → yaptırım',
    trap_word: 'conciliation',
    trap_explanation: '"enforcement" = zorunlu uygulama (güç); "conciliation" = barışçıl uzlaşma (yumuşak)',
    template_sentences: [
      'Stricter ____ of environmental regulations is needed to reduce industrial pollution.',
      'The ____ of speed limits on highways significantly reduced accident rates.',
    ],
  },
  controversy: {
    meaning_tr: 'tartışma, anlaşmazlık, kamuoyu tartışması',
    field: 'dispute / debate',
    collocations: ['cause controversy', 'generate controversy', 'political controversy', 'stir controversy'],
    memory_trick: 'CONTRO + VERSY → "iki taraf birbirine KARŞI" → tartışma',
    trap_word: 'conciliation',
    trap_explanation: '"controversy" = tartışma var; "conciliation" = tartışmayı çözme — zıt',
    template_sentences: [
      'The proposed policy generated considerable ____ among scientists and policymakers alike.',
    ],
  },
  rejection: {
    meaning_tr: 'red, kabul etmeme, geri çevirme',
    field: 'refusal / denial',
    collocations: ['face rejection', 'rejection of an idea', 'organ rejection', 'social rejection'],
    memory_trick: 'RE-JECT → "geri atmak" → RE = geri, JECT = atmak = REDDETMEK',
    trap_word: 'enforcement',
    trap_explanation: '"rejection" = reddetmek; "enforcement" = uygulamak — zıt yönler',
    template_sentences: [
      'The committee\'s ____ of the proposal surprised many experts in the field.',
    ],
  },
  indications: {
    meaning_tr: 'belirtiler, işaretler, göstergeler',
    field: 'signs / evidence',
    collocations: ['clear indications', 'early indications', 'indications of', 'give indications'],
    memory_trick: 'INDICATE → "göstermek" → indications = GÖSTERGELER, belirtiler',
    trap_word: 'installations',
    trap_explanation: '"indications" = işaretler/kanıtlar; "installations" = kurulmuş tesisler — tamamen farklı',
    template_sentences: [
      'There are early ____ that the new treatment may be effective against the virus.',
    ],
  },
  installations: {
    meaning_tr: 'tesisler, kurulumlar, yerleşimler',
    field: 'infrastructure / facility',
    collocations: ['military installations', 'solar installations', 'new installations'],
    memory_trick: 'INSTALL + ATIONS → "kurulan tesisler" → KURULUMLAR',
    trap_word: 'indications',
    trap_explanation: '"installations" = fiziksel tesisler; "indications" = soyut belirtiler — farklı',
    template_sentences: [
      'The military ____ along the border were upgraded with new surveillance equipment.',
    ],
  },
  associations: {
    meaning_tr: 'ilişkiler, bağlantılar; dernekler, birlikler',
    field: 'connection / organization',
    collocations: ['professional associations', 'trade associations', 'free associations', 'make associations'],
    memory_trick: 'ASSOCIATE → "ilişkilendirmek" → associations = BAĞLANTILLAR, birlikler',
    trap_word: 'indications',
    trap_explanation: '"associations" = bağlantılar/örgütler; "indications" = belirtiler/kanıtlar',
    template_sentences: [
      'Researchers found strong ____ between sleep quality and academic performance.',
    ],
  },
  proportions: {
    meaning_tr: 'oranlar, büyüklük, boyutlar',
    field: 'size / ratio',
    collocations: ['reach epidemic proportions', 'in equal proportions', 'massive proportions'],
    memory_trick: 'PROPORTION → "pay/oran" → ORANLAR, büyüklük',
    trap_word: 'associations',
    trap_explanation: '"proportions" = büyüklük/oran; "associations" = bağlantı/birlik — farklı',
    template_sentences: [
      'The problem has grown to alarming ____ that require immediate government action.',
    ],
  },
  enriched: {
    meaning_tr: 'zenginleştirilmiş, güçlendirilmiş',
    field: 'improvement / addition',
    collocations: ['enriched soil', 'enriched diet', 'culturally enriched', 'uranium enriched'],
    memory_trick: 'EN + RICH + ED → "zengin hale getirilmiş" → ZENGİNLEŞTİRİLMİŞ',
    trap_word: 'retained',
    trap_explanation: '"enriched" = daha iyi hale getirmek; "retained" = olduğu gibi korumak — farklı yön',
    template_sentences: [
      'The soil was ____ with organic compost before planting to improve crop yield.',
    ],
  },
  retained: {
    meaning_tr: 'korunmuş, saklanmış, muhafaza edilmiş',
    field: 'preservation / keeping',
    collocations: ['retain moisture', 'retain heat', 'retain employees', 'retain information'],
    memory_trick: 'RE + TAIN → "tutmak" → yeniden tutma = KORUMA, saklama',
    trap_word: 'enriched',
    trap_explanation: '"retained" = değişmeden TUTMAk; "enriched" = iyileştirerek GELİŞTİRMEK',
    template_sentences: [
      'Despite the renovation, the building ____ much of its original Victorian character.',
    ],
  },
  indulged: {
    meaning_tr: 'kendini kaptırmış, zevke dalmış, şımarttığı',
    field: 'excess / pleasure',
    collocations: ['indulge in pleasure', 'indulge a habit', 'indulged child'],
    memory_trick: 'IN + DULGE → "içine dalmak" → aşırı zevk alma, KENDINI KAPRIRMAK',
    trap_word: 'emulated',
    trap_explanation: '"indulged" = kendini bir şeye bırakmak; "emulated" = örnek almak — farklı',
    template_sentences: [
      'After months of dieting, she finally ____ in a slice of chocolate cake.',
    ],
  },
  emulated: {
    meaning_tr: 'taklit edilmiş, örnek alınmış, model alınmış',
    field: 'imitation / admiration',
    collocations: ['emulate a role model', 'widely emulated', 'emulate success'],
    memory_trick: 'EMULATE → "emulatör gibi: orijinali taklit eder" → TAKLIT ETMEK, örnek almak',
    trap_word: 'enriched',
    trap_explanation: '"emulated" = başkasını örnek almak; "enriched" = içeriği geliştirmek — farklı',
    template_sentences: [
      'Her innovative teaching methods were ____ by educators across the country.',
    ],
  },
  encapsulated: {
    meaning_tr: 'özetlenmiş, kapsüle alınmış, içine sıkıştırılmış',
    field: 'summary / containment',
    collocations: ['neatly encapsulated', 'encapsulated in a phrase', 'encapsulated within'],
    memory_trick: 'EN + CAPSULE + D → "bir kapsüle konmuş" → özlü biçimde ÖZETLENMİŞ',
    trap_word: 'retained',
    trap_explanation: '"encapsulated" = özetlemek/sıkıştırmak; "retained" = korumak — farklı',
    template_sentences: [
      'The entire philosophy of the movement was ____ in a single famous speech.',
    ],
  },

  // ── LINKERS / DISCOURSE MARKERS ─────────────────────────────────────────────
  however: {
    meaning_tr: 'ancak, fakat, bununla birlikte',
    field: 'contrast',
    collocations: ['however, ...', '... however, ...'],
    memory_trick: 'HOW-EVER → "ne kadar yaparsan yap, AMA..." → ZITLIK',
    trap_word: 'therefore',
    trap_explanation: '"however" = zıtlık (durum A, AMA durum B); "therefore" = nedensellik (A yüzünden B)',
    template_sentences: [
      'Scientists agree that the Earth is warming; ____, the exact pace remains debated.',
      'The medicine is effective; ____, it has several serious side effects.',
    ],
  },
  furthermore: {
    meaning_tr: 'üstelik, dahası, bunun yanı sıra',
    field: 'addition',
    collocations: ['furthermore, ...', 'and furthermore'],
    memory_trick: 'FURTHER + MORE → "dahası, daha fazlası" → EK BİLGİ ekler',
    trap_word: 'however',
    trap_explanation: '"furthermore" = aynı yönde ek bilgi; "however" = zıt yönde bilgi — farklı mantık',
    template_sentences: [
      'The drug is affordable; ____, it has minimal side effects compared to alternatives.',
    ],
  },
  therefore: {
    meaning_tr: 'bu nedenle, dolayısıyla, bu yüzden',
    field: 'cause-result',
    collocations: ['therefore, ...', 'and therefore'],
    memory_trick: 'THERE + FORE → "oradan ÖNCE gelen sebep" → SONUÇ bağlacı',
    trap_word: 'however',
    trap_explanation: '"therefore" = önceki cümle neden, bu cümle sonuç; "however" = öncekiyle çelişki',
    template_sentences: [
      'The experiment yielded no significant results; ____, the hypothesis was rejected.',
    ],
  },
  'for instance': {
    meaning_tr: 'örneğin, mesela',
    field: 'exemplification',
    collocations: ['for instance, ...', '... for instance, ...'],
    memory_trick: '"FOR INSTANCE" = "bir örnek için bakarsak" → ÖRNEK VERMEK',
    trap_word: 'however',
    trap_explanation: '"for instance" = örnek verir; "however" = zıtlık gösterir — farklı mantık',
    template_sentences: [
      'Many countries have strict regulations against pollution; ____, Germany imposes heavy fines.',
    ],
  },
  thatis: {
    meaning_tr: 'yani, başka bir deyişle',
    field: 'clarification / restatement',
    collocations: ['that is, ...', 'that is to say'],
    memory_trick: '"THAT IS" = "o şudur ki" → yani, AÇIKLAMA yapıyor',
    trap_word: 'therefore',
    trap_explanation: '"that is" = aynı şeyi farklı söylemek; "therefore" = nedensellik — farklı',
    template_sentences: [
      'The study used a qualitative method; ____, interviews and observations were the main tools.',
    ],
  },
  'even though': {
    meaning_tr: 'olmasına karşın, olmasına rağmen',
    field: 'concession / contrast',
    collocations: ['even though + subject + verb', 'even though it seems...'],
    memory_trick: '"EVEN THOUGH" = "hatta buna rağmen" → kabul edip ZITLIK kuruyor',
    trap_word: 'as if',
    trap_explanation: '"even though" = gerçek bir zıtlık (gerçek durum karşısında zıt sonuç); "as if" = sanki (hayali)',
    template_sentences: [
      '____ the treatment was experimental, patients reported significant improvements.',
    ],
  },
  'as if': {
    meaning_tr: 'sanki, güya, -mış gibi',
    field: 'comparison / hypothetical',
    collocations: ['as if + past tense', 'behave as if', 'look as if'],
    memory_trick: '"AS IF" = "SANKI öyleymiş gibi" → hayali karşılaştırma',
    trap_word: 'even though',
    trap_explanation: '"as if" = gerçek olmayan durum; "even though" = gerçek ama zıt durum',
    template_sentences: [
      'He spoke about the project ____ he had already completed it.',
    ],
  },
  'as long as': {
    meaning_tr: 'olduğu sürece, koşuluyla, eğer',
    field: 'condition',
    collocations: ['as long as + present tense', 'as long as you...'],
    memory_trick: '"AS LONG AS" = "o uzunlukta kaldığı sürece" → KOŞUL bildiriyor',
    trap_word: 'since',
    trap_explanation: '"as long as" = koşul (şart); "since" = sebep veya zaman — farklı',
    template_sentences: [
      'The experiment will continue ____ the funding remains available.',
    ],
  },
  'in case': {
    meaning_tr: 'ihtimale karşı, -ihtimaline karşı',
    field: 'precaution / condition',
    collocations: ['in case + subject + verb', 'just in case', 'in case of emergency'],
    memory_trick: '"IN CASE" = "durumda hazır olmak için" → İHTİMALE KARŞI önlem',
    trap_word: 'as long as',
    trap_explanation: '"in case" = olmayabilir ama hazır olmak için; "as long as" = süreç koşulu',
    template_sentences: [
      'Carry an umbrella ____ it rains this afternoon.',
    ],
  },
  since: {
    meaning_tr: '-den beri; çünkü, -dığı için',
    field: 'time / cause',
    collocations: ['since then', 'since + time', 'since + clause (reason)'],
    memory_trick: 'SINCE = hem "zamandan beri" hem "çünkü" → BAĞLAM belirler',
    trap_word: 'although',
    trap_explanation: '"since" = sebep veya zaman; "although" = zıtlık — farklı mantık',
    template_sentences: [
      '____ the data was incomplete, the researchers had to repeat the study.',
    ],
  },
  'on behalf of': {
    meaning_tr: 'adına, namına',
    field: 'representation',
    collocations: ['on behalf of + noun', 'speak on behalf of', 'act on behalf of'],
    memory_trick: '"ON BEHALF OF" = "arkasında durmak" → birinin ADINA hareket etmek',
    trap_word: 'instead of',
    trap_explanation: '"on behalf of" = o kişinin adına; "instead of" = o kişinin yerine/alternatifi olarak',
    template_sentences: [
      'The lawyer spoke ____ her client in the hearing.',
    ],
  },
  'instead of': {
    meaning_tr: 'yerine, -in yerine',
    field: 'substitution / alternative',
    collocations: ['instead of + noun/gerund', 'use X instead of Y'],
    memory_trick: '"INSTEAD OF" = "in + stead (yer)" → onun YERİNE',
    trap_word: 'on behalf of',
    trap_explanation: '"instead of" = alternatif seçim; "on behalf of" = temsil — farklı',
    template_sentences: [
      'The doctor recommended natural remedies ____ antibiotics for minor infections.',
    ],
  },
  despite: {
    meaning_tr: 'rağmen, karşın',
    field: 'concession / contrast',
    collocations: ['despite + noun/gerund', 'despite the fact that'],
    memory_trick: 'DESPITE = DE + SPITE → "kötü niyete (spite) rağmen devam etmek" → RAĞMEN',
    trap_word: 'instead of',
    trap_explanation: '"despite" = buna rağmen (zıtlık); "instead of" = alternatif seçim — farklı',
    template_sentences: [
      '____ numerous obstacles, the team completed the project ahead of schedule.',
    ],
  },
  'so that': {
    meaning_tr: 'böylece, amacıyla, -sın diye',
    field: 'purpose / result',
    collocations: ['so that + subject + verb', 'do X so that Y'],
    memory_trick: '"SO THAT" = "öyle ki... / amacıyla" → AMAÇ veya SONUÇ',
    trap_word: 'because',
    trap_explanation: '"so that" = amaç (niyet); "because" = sebep (geçmiş neden) — farklı yön',
    template_sentences: [
      'The instructions were written clearly ____ even beginners could follow them.',
    ],
  },
  'as a result of': {
    meaning_tr: 'sonucu olarak, -nın bir sonucu olarak',
    field: 'cause-effect',
    collocations: ['as a result of + noun', 'directly as a result of'],
    memory_trick: '"AS A RESULT OF" = "nedenin SONUCU olarak" → nedensellik bağlacı',
    trap_word: 'in pursuit of',
    trap_explanation: '"as a result of" = bir sebepten kaynaklanan; "in pursuit of" = bir amaç için',
    template_sentences: [
      '____ the new regulations, factories reduced their carbon emissions significantly.',
    ],
  },
  'with regard to': {
    meaning_tr: 'ile ilgili olarak, konusunda',
    field: 'topic reference',
    collocations: ['with regard to + noun', 'with regard to this matter'],
    memory_trick: '"WITH REGARD TO" = "... ile ilgili saygı gösterilerek" → KONU belirtiyor',
    trap_word: 'in contrast with',
    trap_explanation: '"with regard to" = konuya giriş; "in contrast with" = zıtlık karşılaştırması',
    template_sentences: [
      '____ the new findings, the board will reconsider its decision next month.',
    ],
  },
  'in contrast with': {
    meaning_tr: 'aksine, zıt olarak, kıyasla',
    field: 'contrast',
    collocations: ['in contrast with + noun', 'in sharp contrast with'],
    memory_trick: '"IN CONTRAST WITH" = "kontrast içinde" → tam KARŞIT gösterme',
    trap_word: 'with regard to',
    trap_explanation: '"in contrast with" = iki şey arasındaki FARK; "with regard to" = konu referansı',
    template_sentences: [
      '____ their competitors, this company maintained steady growth throughout the recession.',
    ],
  },
  'irrespective of': {
    meaning_tr: 'bağımsız olarak, gözetmeksizin',
    field: 'disregard',
    collocations: ['irrespective of + noun', 'irrespective of the outcome'],
    memory_trick: '"IR-RESPECTIVE-OF" = "saygı göstermeden, dikkate almadan" → BAĞIMSIZ OLARAK',
    trap_word: 'in pursuit of',
    trap_explanation: '"irrespective of" = X\'i dikkate almadan; "in pursuit of" = X\'i hedefleyerek',
    template_sentences: [
      'All citizens have the right to vote, ____ their economic status.',
    ],
  },
  'in pursuit of': {
    meaning_tr: 'peşinde, arayışında, uğruna',
    field: 'goal / chase',
    collocations: ['in pursuit of knowledge', 'in pursuit of happiness', 'in pursuit of success'],
    memory_trick: '"IN PURSUIT OF" = "kovalayarak içinde olmak" → bir hedefin PEŞINDE',
    trap_word: 'irrespective of',
    trap_explanation: '"in pursuit of" = hedefini kovalamak; "irrespective of" = gözetmeksizin — farklı',
    template_sentences: [
      'Millions of people have migrated to cities ____ better job opportunities.',
    ],
  },
  'rather than': {
    meaning_tr: 'yerine, -den ziyade, tercihan',
    field: 'preference / substitution',
    collocations: ['rather than + noun/gerund', 'prefer X rather than Y'],
    memory_trick: '"RATHER THAN" = "daha ziyade... değil de" → TERCİH veya KARŞILAŞTIRMA',
    trap_word: 'instead of',
    trap_explanation: '"rather than" = tercih ifadesi; "instead of" = değiştirme/yer alma — çok yakın ama nüans farkı var',
    template_sentences: [
      'Scientists chose to publish the data online ____ waiting for traditional journal review.',
    ],
  },
  'in comparison with': {
    meaning_tr: 'ile kıyaslandığında, kıyasla',
    field: 'comparison',
    collocations: ['in comparison with + noun', 'in direct comparison with'],
    memory_trick: '"IN COMPARISON WITH" = "karşılaştırma içinde" → KIYASLAMA',
    trap_word: 'in contrast with',
    trap_explanation: '"in comparison with" = genel kıyaslama; "in contrast with" = zıtlık vurgusu',
    template_sentences: [
      '____ previous decades, the current generation is far more tech-savvy.',
    ],
  },
  'except for': {
    meaning_tr: 'hariç, dışında, -den başka',
    field: 'exclusion',
    collocations: ['except for + noun', 'except for the fact that'],
    memory_trick: '"EXCEPT FOR" = "dışarıda bırakarak" → İSTİSNA',
    trap_word: 'as a result of',
    trap_explanation: '"except for" = bir şeyi dışlamak; "as a result of" = nedensellik',
    template_sentences: [
      'All participants completed the survey ____ two who dropped out midway.',
    ],
  },
  although: {
    meaning_tr: 'olmasına rağmen, -e karşın',
    field: 'concession / contrast',
    collocations: ['although + subject + verb', 'although it seems'],
    memory_trick: 'AL + THOUGH → "AL bunu ama aynı zamanda..." → kabul edip ZIT FIKIR söyler',
    trap_word: 'since',
    trap_explanation: '"although" = zıtlık/kabul; "since" = sebep veya zaman — farklı',
    template_sentences: [
      '____ the researchers expected positive results, the data showed no improvement.',
    ],
  },
  'just as': {
    meaning_tr: 'tam olarak, tıpkı, -iken',
    field: 'comparison / timing',
    collocations: ['just as + subject + verb', 'just as important'],
    memory_trick: '"JUST AS" = "tam o sırada" ya da "tıpkı gibi" → ZAMANLAMA veya BENZETME',
    trap_word: 'since',
    trap_explanation: '"just as" = tam o sırada veya benzetme; "since" = sebep/zaman başlangıcı',
    template_sentences: [
      '____ the experiment ended, a power failure disrupted all the recordings.',
    ],
  },
  once: {
    meaning_tr: 'bir kez, ..dığında, ..ar ..maz',
    field: 'time / condition',
    collocations: ['once + subject + verb', 'once completed', 'once a day'],
    memory_trick: '"ONCE" = "bir kez" → hem "bir defa" hem "..dığında" (zaman)',
    trap_word: 'unless',
    trap_explanation: '"once" = ..dığında/gerçekleşince; "unless" = eğer...değilse (koşul)',
    template_sentences: [
      '____ the data was collected, the analysis could begin in earnest.',
    ],
  },
  unless: {
    meaning_tr: 'eğer...değilse, olmadıkça',
    field: 'negative condition',
    collocations: ['unless + subject + verb', 'unless stated otherwise'],
    memory_trick: '"UN + LESS" = "eksi koşul" → eğer O OLMAZSA (negatif şart)',
    trap_word: 'once',
    trap_explanation: '"unless" = negatif koşul; "once" = gerçekleşince (pozitif zaman) — farklı',
    template_sentences: [
      'The project cannot proceed ____ the board approves the budget.',
    ],
  },
  until: {
    meaning_tr: '-e kadar, -ne dek',
    field: 'time limit',
    collocations: ['until + time/event', 'wait until'],
    memory_trick: '"UNTIL" = "hedef zamana kadar" → SÜRE bitişi',
    trap_word: 'once',
    trap_explanation: '"until" = biten noktayı gösterir; "once" = başlangıç noktasını gösterir',
    template_sentences: [
      'The scientists monitored the patients ____ all symptoms had completely disappeared.',
    ],
  },
  because: {
    meaning_tr: 'çünkü, -dığı için, nedeniyle',
    field: 'cause',
    collocations: ['because + subject + verb', 'because of + noun'],
    memory_trick: '"BE-CAUSE" = "nedeni olmak" → neden-sonuç: SEBEP verir',
    trap_word: 'so that',
    trap_explanation: '"because" = gerçekleşmiş bir sebep; "so that" = gelecekteki bir amaç — farklı yön',
    template_sentences: [
      'The experiment was halted ____ the safety committee identified critical flaws.',
    ],
  },
  whether: {
    meaning_tr: '..olup olmadığı, ..mi..mi',
    field: 'alternative / doubt',
    collocations: ['whether + subject + verb', 'whether or not', 'decide whether'],
    memory_trick: '"WHETHER" = "hangi hava?" → iki seçenek arasında SORULAMA / şüphe',
    trap_word: 'although',
    trap_explanation: '"whether" = iki alternatif arasında soru; "although" = zıtlık kabul etme',
    template_sentences: [
      'The researchers questioned ____ the results could be replicated in a different environment.',
    ],
  },
  'as much as': {
    meaning_tr: 'o kadar...ki, kadar (her ne kadar...)',
    field: 'degree / concession',
    collocations: ['as much as + clause', 'as much as I dislike...'],
    memory_trick: '"AS MUCH AS" = "o kadar çok ki" → miktar karşılaştırması veya kabul',
    trap_word: 'so that',
    trap_explanation: '"as much as" = derece/miktar; "so that" = amaç/sonuç',
    template_sentences: [
      '____ the theory appealed to scientists, it lacked empirical support.',
    ],
  },

  // ── GRAMMAR FORMS ───────────────────────────────────────────────────────────
  'to discover': {
    meaning_tr: '(amacıyla) keşfetmek — to-infinitive',
    field: 'grammar: to-infinitive (purpose/subject)',
    collocations: ['named to discover', 'sent to discover', 'managed to discover'],
    memory_trick: '"TO + DISCOVER" = amaç bildiriyor → discovery için gidiş',
    trap_word: 'discovered',
    trap_explanation: '"to discover" = amaç bildirmek için; "discovered" = edilgen geçmiş sıfat — yapı farkı',
    template_sentences: [],
  },
  discovered: {
    meaning_tr: 'keşfedilmiş, bulunmuş (geçmiş sıfat/pasif)',
    field: 'grammar: past participle (passive/adjective)',
    collocations: ['recently discovered', 'discovered in', 'carpet discovered'],
    memory_trick: '"DISCOVERED" = V3 → edilgen ya da sıfat görevinde → KEŞFEDILMIŞ',
    trap_word: 'discovering',
    trap_explanation: '"discovered" = geçmiş sıfat/pasif; "discovering" = aktif devam eden eylem',
    template_sentences: [],
  },
  discovering: {
    meaning_tr: 'keşfeden, keşfederken (aktif -ing)',
    field: 'grammar: -ing participle (active)',
    collocations: ['while discovering', 'by discovering'],
    memory_trick: '"DISCOVERING" = aktif eylem devam ediyor → şu an keşfediyor',
    trap_word: 'discovered',
    trap_explanation: '"discovering" = aktif eylem; "discovered" = pasif/tamamlanmış — farklı yapı',
    template_sentences: [],
  },
  'having discovered': {
    meaning_tr: 'keşfetmiş olduğundan (perfect participle)',
    field: 'grammar: perfect participle (prior action)',
    collocations: ['having discovered that...', 'having discovered the truth'],
    memory_trick: '"HAVING DISCOVERED" = ÖNCE keşfetti, SONRA başka şey oldu → önceki eylem tamamlandı',
    trap_word: 'to discover',
    trap_explanation: '"having discovered" = önceden tamamlanmış; "to discover" = amaca yönelik/sonradan',
    template_sentences: [],
  },
}
